#!/bin/sh

# This is a parser for Dar archives in Midnight Commander. You need
# the GPL dar program (version >= 2.3.0) written by Denis Corbin.

# Author: Guus Jansman (mod Alexey Matveev)

# Limitations:
# - The archive file can not be changed
# - Symbolic and hard links are not handled properly
# - Block and character special files are not handled
# - Files not stored in (differential) backups are not handled
# - Dar files in archives are not handled (due filename restriction)

DAR=dar

# dar expects the basename (without number and extension)
BASENAME="`echo "$2" | sed -e 's/\.[0-9]*\.[Dd][Aa][Rr]$//'`"

mcdarfs_list ()
{

$DAR -l "$BASENAME" -N -Q -as 2>/dev/null | gawk -v uuid=${UID-0} '
BEGIN {}
/^-------/ { next }
/^$/ { next }
{
    if (NR == 1) next

    line=$0

    split(line, record, "] ")

    if ( record[1] != "[Saved") 
    {
        next
    }

    split(record[3], record, " ")

    split(line, rec, "\t")
    split(rec[4], date, " ")

    perm = record[1]
    uid = record[2]

    gid = rec[2]
    size = rec[3]
    
    month = date[2]
    day = date[3]
    year = date[5]
    tm = substr(date[4], 1, 5)

    name = rec[5]

    printf "%s    1 %s %s %8d %3s %02d %04d %s\n", perm, uid, gid, size, month, day, year, name
}'
}

mcdarfs_copyout ()
{
    # Dummy directory necessary since dar cannot output to stdout or named file
    mkdir "$3.dir.tmp"
    chmod 700 "$3.dir.tmp"
    if [ ! -d "$3.dir.tmp" ]; then exit 1; fi
    $DAR -x "$BASENAME" -N -O -Q -wa -g "$2" -R "$3.dir.tmp" >/dev/null 2>&1
    if [ -e "$3.dir.tmp/$2" ]; then
        mv "$3.dir.tmp/$2" "$3"
        rm -rf "$3.dir.tmp"
    else
        rm -rf "$3.dir.tmp"
        exit 1
    fi
}

umask 077
cmd="$1"
shift
case "$cmd" in
    list)    mcdarfs_list    "$@" ;;
    copyout) mcdarfs_copyout "$@" ;;
    *)       exit 1 ;;
esac
exit 0